### ISSUE TITLE
TypeError: sections.find is not a function

### ISSUE THREAD

**Issue by tjhorwood** [nesbtesh/zendesk-to-pdf#2]
When running this script, line 65 fails with the following error:

> var sec = sections.find(function(index){

> TypeError: sections.find is not a function
>     at /Users/taylorhorwood/code/zendesk-to-pdf/index.js:65:23
>     at /Users/taylorhorwood/node_modules/node-zendesk/lib/client/client.js:162:18
>     at Object.async.whilst (/Users/taylorhorwood/node_modules/async/lib/async.js:683:13)
>     at /Users/taylorhorwood/node_modules/node-zendesk/lib/client/client.js:135:11
>     at /Users/taylorhorwood/node_modules/node-zendesk/lib/client/client.js:271:12
>     at checkRequestResponse (/Users/taylorhorwood/node_modules/node-zendesk/lib/client/client.js:238:10)
>     at requestCallback (/Users/taylorhorwood/node_modules/node-zendesk/lib/client/client.js:246:3)
>     at Request._callback (/Users/taylorhorwood/node_modules/node-zendesk/lib/client/client.js:104:5)
>     at Request.self.callback (/Users/taylorhorwood/node_modules/node-zendesk/node_modules/request/request.js:187:22)
>     at emitTwo (events.js:125:13)

**Comment by nesbtesh** [comment]
I just pushed a fix for this, remember that to run this script your knowledge base must have sections
